### ISSUE TITLE
Crash When used flash during scan on android 9.0

### ISSUE THREAD

**Issue by Dmxy** [bitpay/cordova-plugin-qrscanner#252]
When I scan the QR code, I turn on the flash and the scan will crash, error like this:
2019-04-28 10:37:49.381 970-970/? E/Camera2ClientBase: getParameters: attempt to use a locked camera from a different process (old pid 0, new pid 27503)
2019-04-28 10:37:49.382 27503-27664/************ E/AndroidRuntime: FATAL EXCEPTION: CameraThread
    Process: **************, PID: 27503
    java.lang.RuntimeException: getParameters failed (empty parameters)
        at android.hardware.Camera.native_getParameters(Native Method)
        at android.hardware.Camera.getParameters(Camera.java:2281)
        at com.journeyapps.barcodescanner.camera.CameraManager$CameraPreviewCallback.onPreviewFrame(CameraManager.java:103)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1318)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by Dmxy** [comment]
![QQ20190428-103958](https://user-images.githubusercontent.com/9995805/56857842-b395c200-69a4-11e9-8510-0315c6acf074.png)

**Comment by pravinkumarputta** [comment]
I'm also facing the same issue on some devices.
```
java.lang.RuntimeException: 
  at android.hardware.Camera.native_getParameters (Native Method)
  at android.hardware.Camera.getParameters (Camera.java:2281)
  at com.journeyapps.barcodescanner.camera.CameraManager$CameraPreviewCallback.onPreviewFrame (CameraManager.java:103)
  at android.hardware.Camera$EventHandler.handleMessage (Camera.java:1318)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:198)
  at android.os.HandlerThread.run (HandlerThread.java:65)
```
Is there any solution to this??
