### ISSUE TITLE
Android : App Crashes - Repeated start and stop the scan.

### ISSUE THREAD

**Issue by Pradeepshivaram** [bitpay/cordova-plugin-qrscanner#296]
Hi,
 In the Android platform, app crashes if I frequently(Ex: 8 ) start and stop the scan.

I see below error in the log.( Command : adb logcat --buffer=crash )
This is in the destroy function in QRScanner.java file.

`01-11 09:02:02.848 15103 15103 E AndroidRuntime: Process: io.ionic.starter, PID: 15103
01-11 09:02:02.848 15103 15103 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeView(android.view.View)' on a null object reference
01-11 09:02:02.848 15103 15103 E AndroidRuntime:     at com.bitpay.cordova.qrscanner.QRScanner$28.run(QRScanner.java:780)
01-11 09:02:02.848 15103 15103 E AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:873)
01-11 09:02:02.848 15103 15103 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
01-11 09:02:02.848 15103 15103 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:214)
01-11 09:02:02.848 15103 15103 E AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:7037)
01-11 09:02:02.848 15103 15103 E AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
01-11 09:02:02.848 15103 15103 E AndroidRuntime:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
01-11 09:02:02.848 15103 15103 E AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)`

Here is my implementation

`startScanning() { 
   // Optionally request the permission early 
      this.qrScanner.prepare()
      .then((status: QRScannerStatus) => {
        if (status.authorized) {
          // camera permission was granted
          // start scanning
          this.qrScanner.show();
          if (this.sensorQrContainer && this.sensorQrContainer.el && this.sensorQrContainer.el.style) 
         {
            this.sensorQrContainer.el.style.opacity = '0';
          }
          this.qrScanObj = this.qrScanner.scan().subscribe((text: string) => {
              this.stopScanning();
              console.log(text); 
          });
        } else if (status.denied) {
          // camera permission was permanently denied
          this.qrScanner.openSettings();
        } else {
           // permission was denied, but not permanently. You can ask for permission again at a later time.
        }
      }).catch(err => {
        console.log(err);
        this.enabelCameraBtn = true;
      });
  }

stopScanning() {
    if (this.sensorQrContainer && this.sensorQrContainer.el && this.sensorQrContainer.el.style) {
      this.sensorQrContainer.el.style.opacity = '1';
    }
    this.qrScanner.hide(); // hide camera preview
    if (this.qrScanObj) {
      this.qrScanObj.unsubscribe(); // stop scanning
    }
    this.qrScanner.destroy();
  }`

ionic info

`Ionic:

   Ionic CLI                     : 5.4.5 (/Users/idontknow/.nvm/versions/node/v10.16.0/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.10.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, browser 6.0.0, ios 5.0.1
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.2, (and 11 other plugins)

Utility:

   cordova-res : 0.7.0 (update available: 0.8.1)
   native-run  : 0.2.8 (update available: 0.3.0)

System:

   Android SDK Tools : 26.1.1 (/Users/idontknow/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.2
   NodeJS            : v10.16.0 (/Users/idontknow/.nvm/versions/node/v10.16.0/bin/node)
   npm               : 6.9.0
   OS                : macOS High Sierra
   Xcode             : Xcode 10.1 Build version 10B61`

Thanks

**Comment by itismelito** [comment]
Have you find a solution, i have same problem?

**Comment by stefano-8wave** [comment]
This fork fix the problem if someone is still interested: https://github.com/24Consulting/cordova-plugin-qrscanner
