### ISSUE TITLE
Limit qr scan area?

### ISSUE THREAD

**Issue by ajaypancholi** [bitpay/cordova-plugin-qrscanner#375]
I am using the qr scanner from Cordova-plugin-qrscanner and currently if I use it and there are multiple QR-codes closely on top of each other, I point my camera at one and it reads the code above it which is outside of the display on screen but within the cameras view. If however there is no QR-code above the one I want to scan, then it scans the correct one, so it seems like it always scans the top QR-code within the cameras view.

Is there a way to limit the "scan area" to be the same size and area as my camera view on my display?

**Comment by phildittrich** [comment]
@ajaypancholi I had the same problem and hacked a fork (some time ago), that should give you an idea: https://github.com/phildittrich/cordova-plugin-qrscanner

Only the QR codes inside the highlighted rectangle are accepted, works for Android and iOS.

**Comment by Sultanwasifiqbal** [comment]
cant work without the fork ? atleast any scanning options parameters ? and also how to display the scanned text on top of camera and continue for another scan like Cognex Barcode Scanner

**Comment by andreir91** [comment]
No response for @Sultanwasifiqbal ? Would be nice to have it without the fork.

**Comment by henkkelder** [comment]
@phildittrich 

I tried to use your fork but ran into an error when installing the plugin.

`Installing "cordova-plugin-qrscanner" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-qrscanner': Error: Uh oh!
ENOENT: no such file or directory, open 'D:\workspace\opwekkingapp\plugins\cordova-plugin-qrscanner\www\www.min.js'
    at Object.readFileSync (node:fs:441:20)
    at install (D:\workspace\opwekkingapp\node_modules\cordova-android\lib\pluginHandlers.js:162:36)
    at ActionStack.process (D:\workspace\opwekkingapp\node_modules\cordova-common\src\ActionStack.js:55:25)
    at PluginManager.doOperation (D:\workspace\opwekkingapp\node_modules\cordova-common\src\PluginManager.js:111:24)
    at PluginManager.addPlugin (D:\workspace\opwekkingapp\node_modules\cordova-common\src\PluginManager.js:141:21)
    at D:\workspace\opwekkingapp\node_modules\cordova-android\lib\Api.js:155:78
TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('ENOENT')
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at C:\Users\hkelder\AppData\Roaming\npm\node_modules\cordova\bin\cordova:32:22
[ERROR] An error occurred while running subprocess cordova.`

Any hints?
