### ISSUE TITLE
Remove Husky

### ISSUE THREAD

**Issue by gabrielbazan7** [bitpay/cordova-plugin-qrscanner#70]
When the plugin is installed on the Copay project, I'm getting this error when trying to commit on Windows OS: 

```
 git commit -m "example"

> husky - npm run -s commitmsg

C:\Users\Gabriel\Documents\copay\plugins\cordova-plugin-qrscanner\node_modules\validate-commit-msg\lib\getGitFolder.js:8
    throw new Error('Cannot find file ' + gitDirLocation);
    ^

Error: Cannot find file ./.git
    at getGitFolder (C:\Users\Gabriel\Documents\copay\plugins\cordova-plugin-qrscanner\node_modules\validate-commit-msg\lib\getGitFolder.js:8:11)
    at Object.<anonymous> (C:\Users\Gabriel\Documents\copay\plugins\cordova-plugin-qrscanner\node_modules\validate-commit-msg\lib\cli.js:22:42)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

> husky - commit-msg hook failed (add --no-verify to bypass)
> husky - to debug, use 'npm run precommit' 

```

**Comment by bitjson** [comment]
We're using husky just to enforce commit conventions – now that Github allows "Squash and Merge", we could even remove it. (Might make things a bit less complicated for new contributors.)

**Comment by dcousens** [comment]
@bitjson this is annoying when using `git clone` to install this plugin,  it proliferates the commit hooks to the parent project!?

**Comment by bitjson** [comment]
Closing this since it's been a while, but PRs welcome!
